# Generated by Django 3.1.4 on 2020-12-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Secret', 'Secret')], default='Secret', max_length=255)),
                ('salary', models.IntegerField(blank=True)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_hiring', models.DateField(blank=True)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
