# Generated by Django 3.1.4 on 2020-12-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('company1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company1', to='companies.company')),
                ('company2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company2', to='companies.company')),
            ],
        ),
    ]
